name: nomics_api_control
description: NomicsOS API Control server
repository: https://github.com/MidstallSoftware/NomicsOS/tree/master/pkgs/api-control
publish_to: none

environment:
  sdk: ^3.5.1

dependencies:
  shelf: ^1.4.2
  args: ^2.5.0
  shelf_router: ^1.1.4
  shelf_hotreload: ^1.5.0
  posix: ^6.0.1
  shelf_cors_headers: ^0.1.5
  path: ^1.9.0
  postgres: ^3.3.0
  bcrypt: ^1.1.3
  json_path: ^0.7.4
  system_info2: ^4.0.0
  git: ^2.3.0
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.1

executables:
  nomics-api-control: nomics-api-control
